In [ ]:
#python code to compute the difference of 
#two matrices
#this operation is to compute 2a-b
#of matrix a and b 

import numpy as np

#first step is to multiply matrix a by 2
#Multiplication using Numpy also know as vectorization 
#which main aim to reduce or remove the explicit use of for loops
#in the program by which computation becomes faster.

a = [[1], [2], [3]]

#matrix ([1]
#        [2]
#        [3])

a = np.array(a)
a2 = a * 2
print("2a is")
print(a2)

#solve operation 2a - b

#creating first matrix 
A = np.array(a2)

#creating second matrix
b = [[4], [5], [6]]
#matrix ([4]
#        [5]
#        [6])
B = np.array(b)

print("The matrix 2a is")
print(A)
print("matrix b is")
print(B)

#subtracting 2 matrix
print("subtraction of 2a - b")
print(np.subtract(A,B))

2a is
[[2]
 [4]
 [6]]
The matrix 2a is
[[2]
 [4]
 [6]]
matrix b is
[[4]
 [5]
 [6]]
subtraction of 2a - b
[[-2]
 [-1]
 [ 0]]


In [ ]:
#python code to find the unit vector of 
#matrix a 


import numpy as np

a = [[1], [2], [3]]
#matrix([1]
#       [2]
#       [3])

vector = np.array(a)
unit_vector = vector /np.linalg.norm(vector)
print(unit_vector)

[[0.26726124]
 [0.53452248]
 [0.80178373]]


In [2]:
#python code to find the 
#unit vector of a in direction of a 

#Python code to find which rows vectors  form an orthogonal set
#determine which a is an orthogonal matrix we 
#multiply the matrix by its transpose to get the identity matrix.

M = 3
N = 3

def transpose(A, b):
  for i in range(M):
    for j in range(N):
      B[i][j] = A[j][i]

#driver code 
B = [[1, 2, 1],
     [2, 1, -4],
     [3, -2, 1]]


# To store result
B = [[0 for x in range(M)] for y in range(N)]

transpose(A, B)

print("Transpose of the matrix is")
for i in range(N):
  for j in range(M):
    print(B[i][j], " ", end='')
print()

# muliply A by this transpose 

import numpy as np

b = [[1, 2, 1],
     [2, 1, -4],
     [3, -2, 1]]

arr1 = np.array(A)
aT = arr1.transpose()



result = a * aT
print("a aT =", result)


#To find the unit vector in the same 
#direction as a vector, we divide it by its magnitude. 

#To Compute the magnitude

def magnitude(a):
  return math.sqrt(sum(pow(element, 2) for element in a))

print('Magnitude of the Vector:', magnitude(np.array(a)))


#The unit vector in the direction of the a is

def unitVector(a):

  a = [[1], [2], [3]]
#matrix([1]
#       [2]
#       [3])

vec_dir = np.array(a)
mag = magnitute(np.array(a))
newVect = vec_dir/mag

print('Unit Vector of a', newVect)



NameError: ignored

In [ ]:
#python code to find the norm of a Matrix

import numpy as np

#initialize matirx

a = [[1], [2], [3]]
#matrix([1]
#       [2]
#       [3])

mat = np.array(a)

#compute norm of a 

a_norm = np.linalg.norm(mat)

print("matrix Norm")
print(a_norm)


matrix Norm
3.7416573867739413


In [ ]:
#Python code to find the angle of 
#a relative to the positive a 
# vector = i + 3j

#The positive direction of x-axis can be 
#represented usng the following vector representation
#[1,2,3]

#In terms of unit vectors, we can express it as follows
#1i + 2j + 3k where i, j, k , Where, 
#denotes the vector in the direction of the positive x-axis


a = [1, 2, 3]

def dotProduct(a):

#The dot product between two vectors
#<1, 2>.<1,SQR 3 >= 1 + 2 






SyntaxError: ignored

In [ ]:
#Python code to find the direction
#cosine of
#the component of the vector would be
#a1,a2, and a3 where a1 = 1, a2 = 2 and a3 = 3
# cos a = a1 / |a| , cos b = a2 / |a|, cos c = a3 / |a|

import numpy as np
import math

a =[1, 2, 3]

value = np.array(a)
sqrsum = np.sum(value**2)
mag = math.sqrt(sqrsum)

# to find all 3 direction cosines 

dircosine = np.array(a)
cosine = np.array(a) / mag
cos_value = np.cos(cosine)

print("Direction cosines", cosine)
print("for cosine of vectors a1 , a2 and a3", cos_value)




  


Direction cosines [0.26726124 0.53452248 0.80178373]
for cosine of vectors a1 , a2 and a3 [0.96449779 0.86051199 0.69542604]


In [ ]:
#python code to calculate the angle between 
#a and b

import numpy as np
import math

#first calculate the dot product of the two vectors 

a = [1, 2, 3]
#matrix([1]
#       [2]
#       [3])

b = [4, 5, 6]
#matrix([4]
#       [5]
#       [6])

dotP = np.dot(a, b)

#calculate the magnitude of a

value = np.array(a)
sqrsum = np.sum(value**2)
mag = math.sqrt(sqrsum)
 

#calculate the magnitude of b
value = np.array(b)
sqrsum = np.sum(value**2)
magb = math.sqrt(sqrsum)

#To calculate the angle between a and b 
# Cos a.b /||a|| ||b||

#product of the maganitude

mag_product = mag * magb
cos_ab = dotP / mag_product
result = math.acos(cos_ab)

print(result)
print("the angle between a and b ", math.degrees(result))
print("The Dot product of the a and b is:", dotP)
print("magnitude of a", mag)
print("magnitude of b", magb)



0.2257261285527342
the angle between a and b  12.933154491899135
The Dot product of the a and b is: 32
magnitude of a 3.7416573867739413
magnitude of b 8.774964387392123


In [ ]:
#python code to calculate the dot product of 
#2 matrices a .b and b . a

import numpy as np

a = [1, 2, 3]
b = [4, 5, 6]

dotP = np.dot(a, b)
dotPb = np.dot(b, a)
print(dotP)
print(dotPb)


32
32


In [4]:
#python code to multiply matrix a and b

def multiply(a,b):
  result = [[0], [0], [0]]

  for i in range(len(a)):

    for j in range(len(b[0])):

      for k in range(len(b)):
        result[i][j] += a[i][j] * b[k][j]

  for p in result:
    print(p)

a = [[1], [2], [3]]

b = [[4], [5], [6]]

print(result)
multiply(a,b)


NameError: ignored

In [ ]:
#python code to multiply matrix b and c

def multiply(b,a):
  result = [[0], [0], [0]]

  for i in range(len(b)):

    for j in range(len(a[0])):

      for k in range(len(a)):
        result[i][j] += a[i][j] * b[k][j]

  for p in result:
    print(p)

b = [[1], [2], [3]]

a = [[4], [5], [6]]

print(result)
multiply(a,b)

[[  1   8   0]
 [  8 -10  30]
 [ -1   3  -3]]
[15]
[30]
[45]


In [ ]:
#python code to calculate the dot product of a . b using
# the angle between a and b 

# we first find the magnitude of both vectors 

import numpy as np
import math


a = [1, 2, 3]
#matrix([1]
#       [2]
#       [3])

b = [4, 5, 6]
#matrix([4]
#       [5]
#       [6])


#calculate the magnitude of a 
value = np.array(a)
sqrsum = np.sum(value**2)
mag = math.sqrt(sqrsum)   


#calculate the magnitude of b
value = np.array(b)
sqrsum = np.sum(value**2)
magb = math.sqrt(sqrsum)

#To calculate the angle between a and b 
# Cos a.b /||a|| ||b||


#product of the maganitude

mag_product = mag * magb
cos_ab = dotP / mag_product
result = math.acos(cos_ab)

print("the angle between a and b ", math.degrees(result))

the angle between a and b  12.933154491899135


In [5]:
from re import S
#python code to find the scaler projection of b onto a

"""A scalar projection is given by the dot product of a 
vector with a unit vector for that direction"""

#in this case the vector is b with the unit vector of a

import numpy as np

a = [[1], [2], [3]]
#matrix([1]
#       [2]
#       [3])

b = [[4], [5], [6]]
#matrix([1]
#       [2]
#       [3])

vector = np.array(a)
unit_vector = vector /np.linalg.norm(vector)

#Scalar projection 

print("The unit vector of a", unit_vector)
print("scalar projection",)


The unit vector of a [[0.26726124]
 [0.53452248]
 [0.80178373]]
scalar projection


In [ ]:
#python code to find the linear dependency between a, b, and c 
# import sympy

"""consider vectors a, b and c where c = a + 2b 
  for any linear conbination of a, b and c such as
  2a + b - c  where c can be replaced by a + 2b"""

from sympy import *

#generate a matrix and get it into row
#echelon form

M = Matrix([[1, 2, 3], [4, 5, 6], [-1, 1, 3]])
print("Matrix : {} ".format(M))

# Use sympy.rref() method
M_rref = M.rref()
	
# The output show two rows with non zero entries 
#this implies a free variable that could be set to anything 
#the set of vectors is linearly dependent

print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref))



Matrix : Matrix([[1, 2, 3], [4, 5, 6], [-1, 1, 3]]) 
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0]]), (0, 1))


A(12) Linear Dependency between a , b and c

In [ ]:
#python code to show the linear dependency

import sympy
import numpy as np
mat = np.array([[1, 2, 3], [4, 5, 6], [-1, 1, 3]])
inds = sympy.Matrix(mat).T.rref()   # to check the rows you need to transpose!


print(inds)
print("this shows row 0 and 1 are linear independant while row 2 isn't")

(Matrix([
[1, 0,  3],
[0, 1, -1],
[0, 0,  0]]), (0, 1))
this shows row 0 and 1 are linear independant while row 2 isn't


A(13) aTb and abT

In [ ]:
#python code to find aT b of 
#where T is the transpose of the matrix

# Python3 Program to find
# transpose of a matrix

M = 3
N = 1

# This function stores
# transpose of A[][] in B[][]

def transpose(A, B):

  for i in range(N):
    for j in range(M):
      B[i][j] = A[j][i]

# driver code
A = [ [1],
[2],
[3]]


# To store result
B = [[0 for x in range(M)] for y in range(N)]

transpose(A, B)

print("Transpose of the matrix is")
for i in range(N):
  for j in range(M):
    print(B[i][j], " ", end='')
print()


# to find the aT b 
# multiply transpose of a by b 
import numpy as np

b = [[4],
     [5],
     [6]]

arr1 = np.array(A)
aT = arr1.transpose()



result = aT * b
print("aT b =", result)

Transpose of the matrix is
1  2  3  
aT b = [[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


In [ ]:
#python code to find the operation abT
#where bT is the transpose b

#Finding the transpose of b 

M = 3
N = 1

def transpose(B, A):
 for i in range(M):
    for j in range(N):
      A[j][i] = B[i][j] 


#driver code 
B = [[4],
     [5],
     [6]]

# to store result

A = [[0 for x in range(M)] for y in range(N)]

transpose (B, A)

print("Transpose of a Matrix b")
for i in range(M):
    for j in range(N):
      print(A[j][i], " ", end='')

# to find a bT
import numpy as np

a = [[1],
     [2],
     [3]]

arr2 = np.array(B)
bT = arr2.transpose()
resultt = a * bT
print("a bT =", result)

Transpose of a Matrix b
4  5  6  a bT = [[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


In [ ]:
#python code to solve the operation 2A - B 
# first multiply 2 vector A

A = [[1, 2, 3],
     [4, -2, 3],
     [0, 5, -1]]

B = [[1, 2, 1],
     [2, 1, -4],
     [3, -2, 1]]

a = np.array(A)
a2 = 2 * a
print("2A =", a2)

# to find 2A - B 
result = np.subtract(a2, B)
print("2A -B =", result)

2A = [[ 2  4  6]
 [ 8 -4  6]
 [ 0 10 -2]]
2A -B = [[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


B(2) AB and BA

In [ ]:
#python code to multiply matrix AB and BA

A = [[1, 2, 3],
     [4, -2, 3],
     [0, 5, -1]]

B = [[1, 2, 1],
     [2, 1, -4],
     [3, -2, 1]]

a = np.array(A)
b = np.array(B)

result = np.multiply(a, b)
result2 = np.multiply(b, a)
print("AB =", result)
print("BA =", result2)

AB = [[  1   4   3]
 [  8  -2 -12]
 [  0 -10  -1]]
BA = [[  1   4   3]
 [  8  -2 -12]
 [  0 -10  -1]]


B(4) This is to find the magnitude of |A| and |c|

In [ ]:
import numpy as np
import math

#first calculate the dot product of the two vectors 

A = [[1, 2, 3],
     [4, -2, 3],
     [0, 5, -1]]

C = [[1, 2, 3],
     [4, 5, 6],
     [-1, 1, 3]]


dotP = np.dot(A, C)
print("dot Product", dotP)

#calculate the magnitude of A

value = np.array(A)
sqrsum = np.sum(value**2)
mag = math.sqrt(sqrsum)
print("|A| =", mag)
 

#calculate the magnitude of C
value = np.array(C)
sqrsum = np.sum(value**2)
magb = math.sqrt(sqrsum)
print("|C| = ", magb)

dot Product [[ 6 15 24]
 [-7  1  9]
 [21 24 27]]
|A| = 8.306623862918075
|C| =  10.099504938362077


This code is to find the transpose of the product of the matrix AB 

In [ ]:
# python code to find the transpose of product 
# of the Matrix AB 

# first find the product of A and b 

A = [[1, 2, 3],
     [4, -2, 3],
     [0, 5, -1]]

B = [[1, 2, 1],
     [2, 1, -4],
     [3, -2, 1]]

a = np.array(A)
b = np.array(B)

result = np.multiply(a, b)
print("Product of AB =", result)
arr1 = np.array(result)
transposeAB = np.transpose(arr1)

print("Transpose of the product of AB",transposeAB)

#to find the product of BT AT ie the product of 
# transpose of B and A 
# first find the transpose of B

arr_trans = np.array(B)
TB = np.transpose(arr_trans)
print("Transpose of Matrix B", TB)

# Transpose of matrix A
arr_trans2 = np.array(A)
TA = np.array(B)
print("Transpose of Matrix A", TA)

#The product of BT and AT

product = np.multiply(TB, TA)
print("BT AT =", product)

Product of AB = [[  1   4   3]
 [  8  -2 -12]
 [  0 -10  -1]]
Transpose of the product of AB [[  1   8   0]
 [  4  -2 -10]
 [  3 -12  -1]]
Transpose of Matrix B [[ 1  2  3]
 [ 2  1 -2]
 [ 1 -4  1]]
Transpose of Matrix A [[ 1  2  1]
 [ 2  1 -4]
 [ 3 -2  1]]
BT AT = [[1 4 3]
 [4 1 8]
 [3 8 1]]


(B5) The following is to find the row vectors that form an orthogonal set.
A matrix is said to be an orthogonal matrix if the product of a matrix and its transpose gives an identity value. 

In [ ]:
#Python code to find which rows vectors  form an orthogonal set
# determine which a is an orthogonal matrix we 
# multiply the matrix by its transpose to get the identity matrix.

M = 3
N = 3

def transpose(A, b):
  for i in range(M):
    for j in range(N):
      B[i][j] = A[j][i]

#driver code 
B = [[1, 2, 1],
     [2, 1, -4],
     [3, -2, 1]]


# To store result
B = [[0 for x in range(M)] for y in range(N)]

transpose(A, B)

print("Transpose of the matrix B is")
for i in range(N):
  for j in range(M):
    print(B[i][j], " ", end='')
print()

# muliply A by this transpose 

import numpy as np

b = [[1, 2, 1],
     [2, 1, -4],
     [3, -2, 1]]

arr1 = np.array(B)
bT = arr1.transpose()



result = b * bT
print("b bT =", result)



Transpose of the matrix B is
1  4  0  2  -2  5  1  3  -1  
b bT = [[  1   4   1]
 [  8  -2 -12]
 [  0 -10  -1]]


In [ ]:
#Python code to find which rows vectors  form an orthogonal set
# determine which a is an orthogonal matrix we 
# multiply the matrix by its transpose to get the identity matrix.

M = 3
N = 3

def transpose(A, b):
  for i in range(M):
    for j in range(N):
      B[i][j] = A[j][i]

#driver code 
A = [[1, 2, 3],
     [4, -2, 3],
     [0, 5, -1]]


# To store result
B = [[0 for x in range(M)] for y in range(N)]

transpose(A, B)

print("Transpose of the matrix A is")
for i in range(N):
  for j in range(M):
    print(B[i][j], " ", end='')
print()

# muliply A by this transpose 

import numpy as np

A = [[1, 2, 1],
     [4, -2, 3],
     [0, 5, -1]]

arr1 = np.array(A)
aT = arr1.transpose()



result = a * aT
print("a aT =", result)



Transpose of the matrix A is
1  4  0  2  -2  5  3  3  -1  
a aT = [[  1   8   0]
 [  8 -10  30]
 [ -1   3  -3]]


In [ ]:
#Python code to find which rows vectors  form an orthogonal set
# determine which a is an orthogonal matrix we 
# multiply the matrix by its transpose to get the identity matrix.

M = 3
N = 3

def transpose(A, b):
  for i in range(M):
    for j in range(N):
      B[i][j] = A[j][i]

#driver code 
C = [[1, 2, 3],
     [4, -2, 3],
     [0, 5, -1]]


# To store result
B = [[0 for x in range(M)] for y in range(N)]

transpose(A, B)

print("Transpose of the matrix C is")
for i in range(N):
  for j in range(M):
    print(B[i][j], " ", end='')
print()

# muliply A by this transpose 

import numpy as np

c = [[1, 2, 3],
     [4, 5, 6],
     [-1, 1, 3]]

arr1 = np.array(C)
cT = arr1.transpose()



result = c * cT
print("a aT =", result)



Transpose of the matrix is
1  4  0  2  -2  5  1  3  -1  
a aT = [[  1   8   0]
 [  8 -10  30]
 [ -3   3  -3]]


This code is to check if a matrix is orthogonal or not , 
we would repeat this for A , B and C 

In [ ]:
# Python code to check
# whether a matrix is
# orthogonal or not

def isOrthogonal(a, m, n) :
	if (m != n) :
		return False
	
	trans = [[0 for x in range(n)]
				for y in range(n)]
				
	# Find transpose
	for i in range(0, n) :
		for j in range(0, n) :
			trans[i][j] = a[j][i]
			
	prod = [[0 for x in range(n)]
			for y in range(n)]
				
	# Find product of a[][]
	# and its transpose
	for i in range(0, n) :
		for j in range(0, n) :
	
			sum = 0
			for k in range(0, n) :
		
				# Since we are multiplying
				# with transpose of itself.
				# We use
				sum = sum + (a[i][k] *
							a[j][k])
	
			prod[i][j] = sum

	# Check if product is
	# identity matrix
	for i in range(0, n) :
		for j in range(0, n) :

			if (i != j and prod[i][j] != 0) :
				return False
			if (i == j and prod[i][j] != 1) :
				return False

	return True

# Driver Code
a = [[1, 2, 3],
     [4, -2, 3],
     [0, 5, -1]]
		
if (isOrthogonal(a, 3, 3)) :
	print ("Yes")
else :
	print ("No")



No


In [ ]:
# Python code to check
# whether a matrix is
# orthogonal or not

def isOrthogonal(a, m, n) :
	if (m != n) :
		return False
	
	trans = [[0 for x in range(n)]
				for y in range(n)]
				
	# Find transpose
	for i in range(0, n) :
		for j in range(0, n) :
			trans[i][j] = a[j][i]
			
	prod = [[0 for x in range(n)]
			for y in range(n)]
				
	# Find product of a[][]
	# and its transpose
	for i in range(0, n) :
		for j in range(0, n) :
	
			sum = 0
			for k in range(0, n) :
		
				# Since we are multiplying
				# with transpose of itself.
				# We use
				sum = sum + (a[i][k] *
							a[j][k])
	
			prod[i][j] = sum

	# Check if product is
	# identity matrix
	for i in range(0, n) :
		for j in range(0, n) :

			if (i != j and prod[i][j] != 0) :
				return False
			if (i == j and prod[i][j] != 1) :
				return False

	return True

# Driver Code
b = [[1, 2, 1],
	[2, 1, -4],
	[3, -2, 1]]
		
if (isOrthogonal(a, 3, 3)) :
	print ("Yes")
else :
	print ("No")




No


In [ ]:
# Python code to check
# whether a matrix is
# orthogonal or not

def isOrthogonal(a, m, n) :
	if (m != n) :
		return False
	
	trans = [[0 for x in range(n)]
				for y in range(n)]
				
	# Find transpose
	for i in range(0, n) :
		for j in range(0, n) :
			trans[i][j] = a[j][i]
			
	prod = [[0 for x in range(n)]
			for y in range(n)]
				
	# Find product of a[][]
	# and its transpose
	for i in range(0, n) :
		for j in range(0, n) :
	
			sum = 0
			for k in range(0, n) :
		
				# Since we are multiplying
				# with transpose of itself.
				# We use
				sum = sum + (a[i][k] *
							a[j][k])
	
			prod[i][j] = sum

	# Check if product is
	# identity matrix
	for i in range(0, n) :
		for j in range(0, n) :

			if (i != j and prod[i][j] != 0) :
				return False
			if (i == j and prod[i][j] != 1) :
				return False

	return True

# Driver Code
a = [[1, 2, 3],
	[4, 5, 6],
	[-1, 1, 3]]
		
if (isOrthogonal(a, 3, 3)) :
	print ("Yes")
else :
	print ("No")




No


B(6) find the inverse of Matrix A and B 

In [30]:
# Python program to inverse
# a matrix using numpy

import numpy as np

a = [[1, 2, 3],
     [4, -2, 3],
     [0, 5, -1]]

b = [[1, 2, 1],
     [2, 1, -4],
     [3, -2, 1]]


# Taking a 3 * 3 matrix

A = np.array(a)

B = np.array(b)


# Calculating the inverse of the matrix
print("the Inverse of Matrix A", np.linalg.inv(A))
print("the Inverse of Matrix B", np.linalg.inv(B))



the Inverse of Matrix A [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
the Inverse of Matrix B [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


In [10]:
#python code to find the inverse 
# of c 

import numpy as np

c = [[1, 2, 3],
     [4, 5, 6],
     [-1, 1, 3]]

C = np.array(c)

Mainv = np.linalg.inv(C)


print(Mainv)

LinAlgError: ignored

B(8) the product of A d

In [11]:
#python code to find the product  of 
# A and d 

import numpy as np

A = [[1, 2, 3],
     [4, -2, 3],
     [0, 5, -1]]

d = [[1],
     [2],
     [3]]

Ad = np.multiply(A, d)
print(Ad)

[[ 1  2  3]
 [ 8 -4  6]
 [ 0 15 -3]]


B(9) The scalar Projection of the rows of A unto the vector d 
the scalar projection is pA(d) = |d|cos(0)  =  A . d/ |d|


In [8]:
#python code to calculate the scalar projection of the rows of A unto 
#rows d

import numpy as np
import math


A = [[1, 2, 3],
     [4, -2, 3],
     [0, 5, -1]]

d = [[1],
     [2],
     [3]]

#find the magnitude of A 
value = np.array(A)
sqrsum = np.sum(value**2)
mag = math.sqrt(sqrsum)

print("magnitude of A =", mag)

#find the dot product of A and d
dotP = np.dot(A, d)
print("The Dot Product of A and d = ", dotP)

#the scalar projection of A unto d with normalization of d 

scalPro = dotP / mag
print("scalar Projection = ", scalPro)

magnitude of A = 8.306623862918075
The Dot Product of A and d =  [[14]
 [ 9]
 [ 7]]
scalar Projection =  [[1.68540194]
 [1.08347268]
 [0.84270097]]


B(10) The vector projection of rows of A unto d 

In [11]:
#Python code to calculate the scalar vector of rows A unto d 

import numpy as np
import math

A = [[1, 2, 3],
     [4, -2, 3],
     [0, 5, -1]]

d = [[1],
     [2],
     [3]]
a = np.array(A)
dv = np.array(d)

d_norm = np.sqrt(sum(dv**2))
print("normalization of d = ", d_norm)

proj_of_A_unto_d = (np.dot(a, dv)/d_norm**2)*dv
print("The scalar Vector of A unto d = ", proj_of_A_unto_d)

normalization of d =  [3.74165739]
The scalar Vector of A unto d =  [[1.        ]
 [1.28571429]
 [1.5       ]]


B(11) calculate the linear combination of the columus of A using elements of d

In [3]:
from sympy.solvers.diophantine.diophantine import Linear
#python code to calulate the linear combination of the colums of 
# A using the elements of d 

import numpy as np
import math

A = [[1, 2, 3],
     [4, -2, 3],
     [0, 5, -1]]

#colums of A =

A1 = [[1],
      [4],
      [0]]

A2 = [[2],
      [-2],
      [5]]

A3 = [[3],
      [3],
      [-1]]


d = [[1],
     [2],
     [3]]

a1 = np.array(A1)
a2 = np.array(A2)
a3 = np.array(A3)

#elements of d 
1, 2, 3

licomb1 = a1 * 1
licomb2 = a2 * 2
licomb3 = a3 * 3

print("linear combination of the colums of A  ")
print(licomb1)
print(licomb2)
print(licomb3)



linear combination of the colums of A  
[[1]
 [4]
 [0]]
[[ 4]
 [-4]
 [10]]
[[ 9]
 [ 9]
 [-3]]


B(12) the solutuon x in the equation Bx = d
to find x we divide both sides of the equation by B 

In [9]:
#python code to divide d by B to find x 

import numpy as np

B = [[1, 2, 1],
     [2, 1, -4],
     [3, -2, 1]]

d = [[1],
     [2],
     [3]]

x = np.divide(d, B)
print(x)


[[ 1.   0.5  1. ]
 [ 1.   2.  -0.5]
 [ 1.  -1.5  3. ]]


B(13) the solution for the equation Cx = d 

In [8]:
#python code to divide d by C to find x 

import numpy as np

C = [[1, 2, 3],
     [4, 5, 6],
     [-1, 1, 3]]

d = [[1],
     [2],
     [3]]

x = np.divide(d, C)
print(x)


[[ 1.          0.5         0.33333333]
 [ 0.5         0.4         0.33333333]
 [-3.          3.          1.        ]]


The inverse of matrix of C

C(1) The eigenvalue and corresponding eigenvector

In [ ]:
#python code to find the eigenvalue and corresponding eigenvector

import numpy as np
from numpy.linalg import eig

d = np.array([[1, 2], 
              [3, 2]])
w,v=eig(d)
print('E-value:', w)
print('E-vector', v)

evec = np.array(v)
print(evec)


E-value: [-1.  4.]
E-vector [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


C(3) The Dot product between the eigenvectors of E

In [3]:
#Python code to find the dot product of the 
#eigenvectors of E

#first find the eigenvectors

import numpy as np
from numpy.linalg import eig

e = [[2, -2],
     [-2, 5]]

E = np.array(e)

w,v=eig(e)
print("Eigenvector", v)

eigenvector = np.array(v)
print(eigenvector)

Eigenvector [[-0.89442719  0.4472136 ]
 [-0.4472136  -0.89442719]]
[[-0.89442719  0.4472136 ]
 [-0.4472136  -0.89442719]]


C(4) the property of the eigenvector E and its reason 

C(5) Find the value of the trivial solution to the equation fx = 0 